name: ebisu_cpp_db
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp_db
description: >
  A library that supports code generation of cpp and others
dependencies:
  path: ">=1.3.0<1.4.0"

# custom <ebisu_cpp_db dependencies>
# end <ebisu_cpp_db dependencies>

dev_dependencies:
  unittest: "any"
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_cpp_db dev dependencies>
# end <ebisu_cpp_db dev dependencies>

dependency_overrides:
# custom <ebisu_cpp_db dependency overrides>
# end <ebisu_cpp_db dependency overrides>

transformers:

# custom <ebisu_cpp_db transformers>
# end <ebisu_cpp_db transformers>

