name: ebisu_cpp_db
version: 0.0.9
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/ebisu_cpp_db
description: >
  A library that supports code generation of C++ database access
dependencies:
  path: ">=1.3.0<1.4.0"

# custom <ebisu_cpp_db dependencies>

  quiver: ">=0.21.0<0.22.0"  
  ini: ">=1.0.0<1.2.0"
  github: ">=2.1.2<2.2.0"
  sqljocky: ">=0.11.0<0.12.0"
  magus: "^0.0.14"
  ebisu_cpp: "^0.3.9"
  ebisu: "^0.6.11"

# end <ebisu_cpp_db dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_cpp_db dev dependencies>
  test: "^0.12.0"
  
environment:
  sdk: ">=1.8.0 <2.0.0"

# end <ebisu_cpp_db dev dependencies>

dependency_overrides:
# custom <ebisu_cpp_db dependency overrides>

#  hop:
#    path: /home/dbdavidson/dev/open_source/hop

# end <ebisu_cpp_db dependency overrides>

transformers:

# custom <ebisu_cpp_db transformers>
# end <ebisu_cpp_db transformers>

